# Generated by Django 6.1.1 on 2026-10-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Mobilenumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Productdetails', models.TextField()),
                ('offer_code', models.CharField()),
            ],
        ),
    ]
